<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" tests="11" skipped="0" failures="0" errors="0" timestamp="2020-08-26T03:57:54" hostname="PC-20191023THJJ" time="0.118">
  <properties/>
  <testcase name="configuredThroughNamespace" classname="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" time="0.087"/>
  <testcase name="taskExecutorByBeanName" classname="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" time="0.003"/>
  <testcase name="taskExecutorByBeanType" classname="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" time="0.004"/>
  <testcase name="exceptionHandlerThrowsUnexpectedException" classname="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" time="0.002"/>
  <testcase name="handleExceptionWithCustomExceptionHandler" classname="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" time="0.0"/>
  <testcase name="threadNamePrefix" classname="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" time="0.001"/>
  <testcase name="handleExceptionWithFuture" classname="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" time="0.01"/>
  <testcase name="proxyCreated" classname="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" time="0.0"/>
  <testcase name="handleExceptionWithListenableFuture" classname="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" time="0.009"/>
  <testcase name="invokedAsynchronously" classname="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" time="0.0"/>
  <testcase name="invokedAsynchronouslyOnProxyTarget" classname="org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessorTests" time="0.002"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
