<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.core.NestedExceptionTests" tests="4" skipped="0" failures="0" errors="0" timestamp="2020-08-26T03:58:46" hostname="PC-20191023THJJ" time="0.003">
  <properties/>
  <testcase name="nestedRuntimeExceptionWithRootCause" classname="org.springframework.core.NestedExceptionTests" time="0.001"/>
  <testcase name="nestedCheckedExceptionWithRootCause" classname="org.springframework.core.NestedExceptionTests" time="0.0"/>
  <testcase name="nestedRuntimeExceptionWithNoRootCause" classname="org.springframework.core.NestedExceptionTests" time="0.0"/>
  <testcase name="nestedCheckedExceptionWithNoRootCause" classname="org.springframework.core.NestedExceptionTests" time="0.001"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
